### ISSUE TITLE
flutter 버전 차이에 다른  'FlatButton' isn't defined 에러

### ISSUE THREAD

**Issue by Gongchaeyeon** [2022HUE/Firstick-APP#21]
**[현상]**
플러터 version 3.0.5에서 개발했을 땐 정상적으로 실행되나,
version 3.3.0의 환경에서 실행했을 때 아래의 error가 뜸

> `The method 'FlatButton' isn't defined for the type '_HomeScreenState'.`
> `Try correcting the name to the name of an existing method, or defining a method named 'FlatButton'.`

추후에 tflite와 병합할 때 에러가 난다면 버전 변경 필요

**[재현방법]**
1. main 브랜치 파일들을 로컬로 git pull
2. F5를 눌러 Start Debugging

**[개선방향]**
- [x] flutter version 3.3.0으로 업데이트 or 3.0.5로 다운그레이드
- [ ] version 3.3.0으로 변경할 시 FlatButton이 아닌 다른 위젯으로 변경 시도

**Comment by anjiwon319** [comment]
flutter downgrade 방법
`flutter downgrade <version>`
ex. `flutter downgrade v.3.0.5`

**Comment by ShimHyerin** [comment]
> flutter downgrade 방법 `flutter downgrade <version>` ex. `flutter downgrade v.3.0.5`

**flutter downgrade error**
`There is no previously recorded version for channel "stable". `

[해결]
flutter 설치 경로로 이동(.git이 있는 폴더)
`git checkout <version>`
ex. `git checkout 3.0.5`

`flutter doctor`를 실행하면 정상적으로 다운그레이드가 된 것을 확인할 수 있다.

**Comment by Gongchaeyeon** [comment]
flutter version  3.0.5로 다운그레이드
